controllers:
    resource:
        path: ../src/Controller/
        namespace: App\Controller
    type: attribute

home:
    path: /
    controller: App\Controller\HomeController::index

product_list:
    path: /productos
    controller: App\Controller\ProductController::listProducts    

contact:
    path: /contacto
    controller: App\Controller\ContactController::contact
